spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:7001/product_db
    username: product-service
    password: product-service
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true


server:
  port: 8001

grpc:
  server:
    port: 9001

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthz
  endpoint:
    health:
      show-details: always