spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:7001/product_db
    username: product-service
    password: product-service
    driver-class-name: org.postgresql.Driver

server:
  port: 8001

grpc:
  server:
    port: 9001