spring:
  application:
    name: user-api-gateway

grpc:
  client:
    product-service:
      address: 'static://localhost:9001'
      negotiation-type: plaintext
    order-service:
      address: 'static://localhost:9002'
      negotiation-type: plaintext
    inventory-service:
      address: 'static://localhost:9003'
      negotiation-type: plaintext

jwt:
  secret: 'v7S6A9yB2E5H8KcNfUjXnZr4u7x!A%D*G-'

server:
  port: 8100

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthz
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs